#!/usr/bin/env bash
# generate-index.sh — Generate rules/INDEX.md, skills/INDEX.md, and manifest.json
# Idempotent: safe to re-run. Overwrites generated files each time.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
RULES_DIR="$REPO_ROOT/rules"
SKILLS_DIR="$REPO_ROOT/skills"

# --- Helpers ---

# Extract YAML frontmatter block (lines between the two --- markers, exclusive).
get_frontmatter() {
  awk '/^---$/ { count++; next } count == 1 { print } count >= 2 { exit }'
}

# Extract a single scalar value from frontmatter.
# Usage: extract_fm_value "key" "$frontmatter"
extract_fm_value() {
  local key="$1" fm="$2"
  local val
  val="$(echo "$fm" | awk -v k="$key" '$0 ~ "^"k":" { sub("^"k":[ \t]*", ""); print; exit }')"
  # Strip surrounding quotes
  val="${val#\"}" ; val="${val%\"}"
  val="${val#\'}" ; val="${val%\'}"
  printf '%s' "$val"
}

# Extract a YAML list (inline [a, b] or block - items) from frontmatter.
# Usage: extract_fm_list "key" "$frontmatter"
# Returns values one per line.
extract_fm_list() {
  local key="$1" fm="$2"

  # Check if the key exists at all
  if ! echo "$fm" | grep -q "^${key}:"; then
    return
  fi

  local line
  line="$(echo "$fm" | awk -v k="$key" '$0 ~ "^"k":" { sub("^"k":[ \t]*", ""); print; exit }')"

  # Inline: [a, b, c]
  if [[ "$line" == \[* ]]; then
    echo "$line" | tr -d '[]' | tr ',' '\n' | sed 's/^[[:space:]]*//; s/[[:space:]]*$//' | sed '/^$/d'
    return
  fi

  # Block list: lines starting with "  - " after the key line
  local in_list=0
  while IFS= read -r l; do
    if [[ "$l" == "${key}:"* ]]; then
      in_list=1
      continue
    fi
    if [ "$in_list" -eq 1 ]; then
      if [[ "$l" =~ ^[[:space:]]*-[[:space:]] ]]; then
        echo "$l" | sed 's/^[[:space:]]*-[[:space:]]*//' | sed 's/^"//; s/"$//; s/^'"'"'//; s/'"'"'$//'
      else
        break
      fi
    fi
  done <<< "$fm"
}

# Extract the first H1 heading from file content (after frontmatter).
# Usage: extract_h1 < file
extract_h1() {
  awk '
    /^---$/ { fm++; next }
    fm >= 2 && /^# / { sub(/^# /, ""); print; exit }
  '
}

# Join array items with a delimiter.
# Usage: join_by "," "${arr[@]}"
join_by() {
  local d="$1"; shift
  local first="$1"; shift || true
  printf '%s' "$first"
  for item in "$@"; do
    printf '%s%s' "$d" "$item"
  done
}

# Escape special JSON characters in a string.
json_escape() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

# --- Collect rules ---

declare -a rule_names=()
declare -a rule_scopes=()
declare -a rule_summaries=()
declare -a rule_paths=()
declare -a rule_languages=()
declare -a rule_extends=()

while IFS= read -r file; do
  relpath="${file#"$RULES_DIR/"}"

  # Skip INDEX.md
  [ "$relpath" = "INDEX.md" ] && continue

  fm="$(get_frontmatter < "$file")"
  name="${relpath%.md}"
  scope="$(extract_fm_value "scope" "$fm")"
  summary="$(extract_h1 < "$file")"
  langs="$(extract_fm_list "languages" "$fm" | paste -sd ',' - || true)"
  extends="$(extract_fm_list "extends" "$fm" | paste -sd ',' - || true)"

  [ -z "$scope" ] && scope="universal"

  rule_names+=("$name")
  rule_scopes+=("$scope")
  rule_summaries+=("$summary")
  rule_paths+=("rules/$relpath")
  rule_languages+=("$langs")
  rule_extends+=("$extends")
done < <(find "$RULES_DIR" -name '*.md' -not -name 'INDEX.md' | sort)

# --- Collect skills ---

declare -a skill_names=()
declare -a skill_summaries=()
declare -a skill_scopes=()
declare -a skill_uses_rules=()
declare -a skill_paths=()

while IFS= read -r file; do
  relpath="${file#"$SKILLS_DIR/"}"
  [ "$relpath" = "INDEX.md" ] && continue

  fm="$(get_frontmatter < "$file")"
  name="$(extract_fm_value "name" "$fm")"
  [ -z "$name" ] && name="${relpath%.md}"

  scope="$(extract_fm_value "scope" "$fm")"
  [ -z "$scope" ] && scope="universal"

  uses="$(extract_fm_list "uses_rules" "$fm" | paste -sd ',' - || true)"
  summary="$(extract_h1 < "$file")"

  skill_names+=("$name")
  skill_summaries+=("$summary")
  skill_scopes+=("$scope")
  skill_uses_rules+=("$uses")
  skill_paths+=("skills/$relpath")
done < <(find "$SKILLS_DIR" -maxdepth 1 -name '*.md' -not -name 'INDEX.md' | sort)

# --- Generate rules/INDEX.md ---

{
  echo '<!-- Auto-generated by scripts/generate-index.sh — do not edit manually -->'
  echo ''
  echo '# Rules Index'
  echo ''
  echo '| Rule | Scope | Extends | Summary |'
  echo '|------|-------|---------|---------|'

  # Universal rules first (sorted by name)
  for i in "${!rule_names[@]}"; do
    if [ "${rule_scopes[$i]}" = "universal" ]; then
      echo "| [${rule_names[$i]}](${rule_names[$i]}.md) | universal | ${rule_extends[$i]} | ${rule_summaries[$i]} |"
    fi
  done

  # Language-specific rules (sorted by language then name)
  lang_entries=()
  for i in "${!rule_names[@]}"; do
    if [ "${rule_scopes[$i]}" = "language-specific" ]; then
      lang_entries+=("${rule_languages[$i]}|${rule_names[$i]}|${rule_summaries[$i]}|${rule_extends[$i]}")
    fi
  done

  if [ ${#lang_entries[@]} -gt 0 ]; then
    IFS=$'\n' sorted_lang=($(printf '%s\n' "${lang_entries[@]}" | sort))
    unset IFS

    for entry in "${sorted_lang[@]}"; do
      lang="$(echo "$entry" | cut -d'|' -f1)"
      name="$(echo "$entry" | cut -d'|' -f2)"
      summary="$(echo "$entry" | cut -d'|' -f3)"
      extends="$(echo "$entry" | cut -d'|' -f4)"
      echo "| [${name}](${name}.md) | language-specific (${lang}) | ${extends} | ${summary} |"
    done
  fi
} > "$RULES_DIR/INDEX.md"

echo "Generated $RULES_DIR/INDEX.md"

# --- Generate skills/INDEX.md ---

{
  echo '<!-- Auto-generated by scripts/generate-index.sh — do not edit manually -->'
  echo ''
  echo '# Skills Index'
  echo ''
  echo '| Skill | Uses Rules | Summary |'
  echo '|-------|-----------|---------|'

  for i in "${!skill_names[@]}"; do
    echo "| [${skill_names[$i]}](${skill_names[$i]}.md) | ${skill_uses_rules[$i]} | ${skill_summaries[$i]} |"
  done
} > "$SKILLS_DIR/INDEX.md"

echo "Generated $SKILLS_DIR/INDEX.md"

# --- Generate manifest.json ---

{
  echo '{'
  echo '  "rules": ['

  last_rule=$(( ${#rule_names[@]} - 1 ))
  for i in "${!rule_names[@]}"; do
    comma=","
    [ "$i" -eq "$last_rule" ] && comma=""

    langs="${rule_languages[$i]}"
    extends="${rule_extends[$i]}"

    # Build optional JSON fields
    optional=""

    if [ "${rule_scopes[$i]}" = "language-specific" ] && [ -n "$langs" ]; then
      lang_json="["
      first=1
      IFS=',' read -ra lang_arr <<< "$langs"
      for l in "${lang_arr[@]}"; do
        l="$(echo "$l" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')"
        [ -z "$l" ] && continue
        [ "$first" -eq 0 ] && lang_json+=", "
        lang_json+="\"$(json_escape "$l")\""
        first=0
      done
      lang_json+="]"
      optional+=", \"languages\": ${lang_json}"
    fi

    if [ -n "$extends" ]; then
      ext_json="["
      first=1
      IFS=',' read -ra ext_arr <<< "$extends"
      for e in "${ext_arr[@]}"; do
        e="$(echo "$e" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')"
        [ -z "$e" ] && continue
        [ "$first" -eq 0 ] && ext_json+=", "
        ext_json+="\"$(json_escape "$e")\""
        first=0
      done
      ext_json+="]"
      optional+=", \"extends\": ${ext_json}"
    fi

    echo "    { \"name\": \"$(json_escape "${rule_names[$i]}")\", \"scope\": \"$(json_escape "${rule_scopes[$i]}")\"${optional}, \"path\": \"$(json_escape "${rule_paths[$i]}")\" }${comma}"
  done

  echo '  ],'
  echo '  "skills": ['

  last_skill=$(( ${#skill_names[@]} - 1 ))
  for i in "${!skill_names[@]}"; do
    comma=","
    [ "$i" -eq "$last_skill" ] && comma=""

    uses="${skill_uses_rules[$i]}"
    uses_json="["
    first=1
    if [ -n "$uses" ]; then
      IFS=',' read -ra uses_arr <<< "$uses"
      for u in "${uses_arr[@]}"; do
        u="$(echo "$u" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')"
        [ -z "$u" ] && continue
        [ "$first" -eq 0 ] && uses_json+=", "
        uses_json+="\"$(json_escape "$u")\""
        first=0
      done
    fi
    uses_json+="]"

    echo "    { \"name\": \"$(json_escape "${skill_names[$i]}")\", \"scope\": \"$(json_escape "${skill_scopes[$i]}")\", \"uses_rules\": ${uses_json}, \"path\": \"$(json_escape "${skill_paths[$i]}")\" }${comma}"
  done

  echo '  ]'
  echo '}'
} > "$REPO_ROOT/manifest.json"

echo "Generated $REPO_ROOT/manifest.json"
echo "Done."
